Traceback (most recent call last):
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 274, in <module>
    test_acc, test_std, val_acc, val_std = run(args, hparams, device)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 152, in run
    test_acc, val_acc = train(args, hparams, device)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 76, in train
    algorithm.to(device)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 274, in <module>
    test_acc, test_std, val_acc, val_std = run(args, hparams, device)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 152, in run
    test_acc, val_acc = train(args, hparams, device)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 76, in train
    algorithm.to(device)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 315, in <module>
    test_acc, test_std, val_acc, val_std = run(args, hparams, device)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 152, in run
    test_acc, val_acc = train(args, hparams, device)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 76, in train
    algorithm.to(device)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 315, in <module>
    test_acc, test_std, val_acc, val_std = run(args, hparams, device)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 152, in run
    test_acc, val_acc = train(args, hparams, device)
  File "/cluster/tufts/aeronlab/tnguye34/CS-CMNIST/domainbed/sweep_train.py", line 76, in train
    algorithm.to(device)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/cluster/tufts/aeronlab/tnguye34/condaenv/IBM1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
